name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-flatpak-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive

      - uses: flatpak/flatpak-github-actions/flatpak-builder@79327416609af08178ad73b352877e51450790b3
        with:
          bundle: atoms.flatpak
          manifest-path: pm.mirko.Atoms.yml
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
          artifact-name: atoms-flatpak
